# Generated by Django 4.1.2 on 2022-11-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationmodel",
            name="name",
            field=models.CharField(blank=True, default="unknown", max_length=128),
        ),
    ]
