# Generated by Django 4.1.2 on 2022-11-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_locationmodel_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64)),
                ("place", models.CharField(max_length=64)),
                (
                    "image",
                    models.ImageField(
                        default="default/place.png", upload_to="place/image/"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
