# Generated by Django 4.1.2 on 2022-11-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_delete_placemodel_vehiclemodel_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="slotmodel",
            name="amount",
            field=models.FloatField(default=0.0),
        ),
    ]
