# Generated by Django 4.1.2 on 2022-11-24 11:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_slotmodel_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmodel",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentmodel",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="paymentmodel",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="paymentmodel",
            name="amount",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="paymentmodel",
            name="booking",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="core.bookingmodel",
            ),
        ),
    ]
